const Descriptions = {
	petals: {
		"Basic": "A nice petal, not very strong.",
		"Light": "Very weak, but recharges very quickly.",
		"Stinger": "It hurts a lot, but it takes a while to recharge.",
		"Sand": "Quickly reloading sand particles.",
		"Leaf": "Heals your flower constantly with energy from the sun.",
		"Rock": "Very durable, but takes longer to recharge.",
		"Faster": "It makes your petals spin faster.",
		"Iris": "Slowly takes down anything it hits.",
		"Rice": "Spawns extremely quickly, but very weak.",
		"Heavy": "It's so heavy, nothing gets in the way.",
		"Yucca": "Only heals your flower in the defensive position.",
		"Pincer": "Debilitates enemies temporarily, reducing their speed with poison.",
		"Yin Yang": "Affects the rotation of your petals mysteriously.",
		"Rose": "Can be absorbed by flowers to heal them.",
		"Dahlia": "Can be absorbed by flowers to heal them. Quite consistent.",
		"Trident": "Constantly poisons every enemy in the room. Also permanently angers Sunlit Frogs.",
		"Corn": "Practically unbreakable, but not much damage.",
		"Bone": "Reduces incoming damage to itself with armor.",
		"Token": "Money money money must be funny",
		"Wing": "It comes and goes.",
		"Missile": "You can actually shoot this one.",
		"Fire Missile": "Return it to the queen before it's too late. It's got her poison all over it.",
		"Oranges": "A sweet citrus fruit with some extra range.",
		"Fig": "Explodes on impact, damaging many mobs.",
		"Coconut": "Deals massive damage on its final hit only. 50% less effective on bosses.",
		"Root": "You can't move yourself, and your damage (apart from any damage from your summons) is 50% less, but you gain resistance. Armor percent is applied after all other reductions.",
		"Honey": "A decoy that attracts mobs away from flowers.",
		"Neutron Star": "A decoy that forcefully attracts mobs with the strength of gravity. Free will is just an illusion after all. Aims in your movement direction.",
		"Peas": "A strong 4 in 1 deal. Projectiles have 10x the health and bounce off walls.",
		"Grapes": "A poisonous 4 in 1 deal. Projectiles have 10x the health and bounce off walls and enemies.",
		"Blueberries": "An electric 4 in 1 deal. Projectiles have 10x the health and bounce off walls and enemies.",
		"Pomegranate": "A deadly 4 in 1 deal. Projectiles have 10x the health and bounce off walls and enemies.",
		"Cactus": "Increases your maximum health and also deals lots of damage.",
		"Husk": "A husk of what was once a strong insect. Equipping gives you body armor for mob body damage (non-stackable) and max health.",
		"Toxin": "All mobs that touch you will take poison damage.",
		"Dark Spine": "WIth centuries of evolution, this husk of a coral carries a deadly omen. Instantly kills bosses under a certain %.",
		"Cutter": "Quite spiky. Grants you additional body damage. You do not take knockback from mob or projectile body damage while equipped. Does not stack.",
		"Clover": "Reloads at the start of waves, increasing Lucky Wave chance, which causes double drops. Stacks with other clovers diminishingly. Chance has a minimum of 4 times total squad buff. Lucky & Boss are mutually exclusive.",
		"Horn": "If the current wave has ended, this petal calls for the next wave to start if there are under a certain number of mobs remaining. It also instantly vanquishes all remaining mobs under some rarity without drops.",
		"Dandelion": "Reduces healing effects on its target (reduces heal/s by effect). It's shootable.",
		"Egg": "Hatches into a friendly mob that defends you.",
		"Plastic Egg": "Through advanced technology, summons a plastic.",
		"Jellyfish Egg": "It's gonna zap everything to death. Pet Jellyfish deal 12% of their max health as zap damage.",
		"Web": "It's so sticky, it slows down other mobs.",
		"Pollen": "Asthmatics beware: this petal leaves traces of itself everywhere.",
		"Magnet": "Increases drop pickup range. Does not stack. Defends against electrical attacks.",
		"Stick": "A mysterious stick that summons sandstorms.",
		"Salt": "Reflects damage back to the enemy that dealt it.",
		"Soil": "Increases max health significantly, but also makes you large (does not decrease speed).",
		"Powder": "Increases movement speed, but decreases health. Does not stack.",
		"Shade": "The remains of a dark soul. Upon being killed, hold on to life for just a bit longer. Damage taken as a shadow is counted as a quarter. Cannot revive other flowers while being a shadow, and cannot be revived shortly after death. Does not stack.",
		"Radiance": "The remains of a bright soul. Every wave fully survived adds extra hp, with a max of 10 waves. Does not stack.", 
		"Dust": "Covers yourself in dust, causing all mobs to recalculate which flower they target. During this recalculation, you have 1/4 priority.",
		"Mandible": "Has a 10% chance of doing 20x damage. Critical chance increases to 20% when 3 or more flowers are dead.",
		"Third Eye": "Increases petal range. Does not stack.",
		"Bud": "Slowly grows back into a flower, reviving dead teammates.",
		"Bloom": "Grows back into a bouquet of lies, if you will. Revives all dead teammates.",
		"Square": "That's the wrong game!",
		"Pentagon": "That's definitely the wrong game!",
		"Ikea": "Home to the world's greatest Swedish Meatballs!",
		"Rubber": "If a mob hits your flower, it gets bounced away. Does not stack, works while on reload.",
		"Shell": "Grants a shield, giving additional HP. Shield slowly decays while active.",
		"Sponge": "Absorbs 90% of incoming damage and deals it over time. Does not stack. If all sponges equipped die, all absorbed damage is instantly dealt.",
		"Pearl": "Recharges at the start of waves if equipped (excluding spawn wave). Deals 50% less damage to bosses.",
		"Jelly": "Upon contact, repels whatever it touched from the flower.",
		"Fangs": "All damage dealt by this petal heals the flower by the lifesteal %.",
		"Jolt": "Once absorbed, teleports you across the map, then cannot be absorbed again for some time",
		"Lightning": "Activates upon contact with an enemy or projectile. Bounces on enemies and projectiles. Lightning ignores Ant Burrows.",
		"Claw": "Deals a percentage of the mob's remaining health, with a maximum.",
		"Starfish": "Heals the flower but only when it's under 70% health",
		"Air": "It's just air. Inflates you but makes you lose much of your max health, relative to the inflation. Unstackable.",
		"Bubble": "Propels the flower in the opposite direction while in defense mode",
		"Shiny Bubble": "Propels the flower in the direction you are facing",
		"Coral": "Converts a percentage of overheal into shield, does not stack. Deals % extra damage based on % health.",
		"Compass": "Glows the color of the highest rarity due to spawn in a wave.",
		"Dark Compass": "Glows the color of the lowest rarity due to spawn in a wave.",
		"Waterlogged Compass": "Shows you the number of the highest rarity mobs spawning in a wave.",
		"Thomas": "Poor Thomas was going faster than he had ever gone before. He was out of breath and his wheels hurt him, but he had to go on. ‘I shall never be the same again,’ he thought sadly. ‘My wheels will be quite worn out.’ ",
		"Card": "This credit card oozes wealth, attracting the plebeian enemies so much that they spawn faster. Does not stack. Only obtainable through the flowr.fun discord server.",
		"Mini Flower": "uwu so cute <3",
		"Ruby": "A mythical gem infused with the power of friendship.",
		"Sapphire": "A mythical gem infused with the power of transformation.",
		"Emerald": "A mythical gem infused with the power of genesis.",
		"Amulet of Divergence": "An ancient relic believed to have the power of creating a false reality. Limited use per player per game. (Attack or defend to absorb differently; only usable after wave spawning ends; new spawn-waves do not save after use)",
		"Amulet of Grace": "Grants maximum grace mana with diminishing returns. An ancient relic believed to have the power of delaying the inevitable, costing more grace mana if the wave is higher and/or the inevitable is delayed for longer. If mana cost is too high, delay only works partially. Mana is per flower.",
		"Amulet of Time": "Grants maximum time mana with diminishing returns. An ancient relic believed to have the power of manipulating time. Slows down every mob by 50% until the next wave, costing more time mana if the wave is higher and/or the amulet is used earlier in the wave. Mana is per flower.",
		"Blood Stinger": "This stinger demands a sacrifice... Each hit deals damage back to the flower.",
		"Blood Leaf": "This leaf is imbued with the blood of the fallen, growing 1% stronger every life the squad takes. Eventually your shoulders will crumble beneath the weight of your sins. Sins reset if all leaves are unequipped, or upon death.",
		"Blood Corn": "This corn grows darker by the second. For every second this corn lives, it deals 2% more damage but 4% more self-damage. Caps at 1 minute.",
		"Blood Light": "This light demands a sacrifice... Each hit deals damage back to the flower.",
		"Blood Rose": "If enough mobs die before the rose absorbs, you get stacking temporary healing. Failing removes previous stacks & deals self-damage.",
		"Shiny Wing": "The faster it goes, the more damage it does!",
		"Cash": "The sense of cash attracts higher rarity mobs. Their greed forces the room in to higher waves.",
		"Shard of Divergence": "The instability of this shard destroys the fabric of reality, revealing the in-between. The transformation rips the shard to atoms, destroying it permanently.",
		"Shard of Time": "This shard rips open the space-time continuum. The room falls through, re-emerging at an earlier wave. During this process, the shard is lost to the void...",
		"Shard of Grace": "Upon usage, this shard prevents an untimely demise. The next wave is forced back, instilling a sense of hope and relief. This, however, shatters the shard, starting the next wave.",
		"Blossom": "This magical petal absorbs any poison the flower might contain! Absorbed poison damages the petal.",
		"Shiny Leaf": "It's incredibly efficient at absorbing energy from the sun, boosting your current healing! Doesn't stack.",
		"Carapace": "Taken off a dead crab, this odd shell seems to have some regenerative properties...",
		"Lilypad": "This odd petal seems to have some regenerative properties... but for pets!",
		"Trinket of the Hivemind": "You can hear distant humming within the trinket... Converts Soldier Ant summons into Soldier Termites",
		"Trinket of the Sea": "The sounds of the sea fills your ears... Converts Sandstorm summons into Whirlpools",
		"Trinket of the Wild": "A faint grassy smell is emitted from this trinket... Duped summons have half hp and half damage, and die when the parent summon dies.",
		"Ant Egg": "\"Borrowed\" from a queen ant, so that you can lead your own army of ants!",
		"Waterlogged Dark Compass": "Shows you the number of the lowest rarity mobs spawning in a wave.",
		"Plank": "This plank is fresh off the mill with a cut so fine that it does 100x damage to projectiles and petals!",
		"Carrot": "This tasty vegetable is incredibly dense! I wonder what it could do if fired..."
	},
	tanksmiths: {
		"Basic": "A nice petal, not very strong.",
		"Light": "Very weak, but recharges very quickly.",
		"Stinger": "It hurts a lot, but it takes a while to recharge.",
		"Sand": "Quickly reloading quadruple shoot!",
		"Leaf": "Heals your flower constantly with energy from the sun.",
		"Rock": "Very durable, but takes longer to recharge. Very tanky.",
		"Faster": "It makes all projectiles travel faster.",
		"Iris": "Slowly takes down anything it hits.",
		"Rice": "Spawns extremely quickly, but very weak.",
		"Heavy": "It's so heavy, nothing gets in the way.",
		"Yucca": "Passively heals all alive tanks.",
		"Pincer": "Debilitates enemies temporarily, reducing their speed with poison.",
		"Yin Yang": "Causes your tanks to moonwalk, shooting stuff in the opposite direction of their barrels.",
		"Rose": "Currently quite buggy.",
		"Dahlia": "Currently quite buggy.",
		"Trident": "Doesn't work right now.",
		"Corn": "Is that a tri-angle?",
		"Bone": "Reduces incoming damage to its bullets with armor.",
		"Token": "Money money money must be funny",
		"Wing": "Doesn't do anything special yet.",
		"Missile": "Unfortunately quite boring now since every petal can be shot.",
		"Fire Missile": "Return it to the queen before it's too late. It's got her poison all over it.",
		"Oranges": "A sweet citrus fruit which reloads quickly.",
		"Fig": "Explodes on impact, damaging many mobs.",
		"Coconut": "Deals massive damage on its final hit only. 50% less effective on bosses.",
		"Root": "You can't move yourself, and your damage (apart from any damage from your summons) is 50% less, but you gain resistance. Armor percent is applied after all other reductions.",
		"Honey": "Bugged.",
		"Neutron Star": "A decoy that forcefully attracts mobs with the strength of gravity. Free will is just an illusion after all. Works up to equal rarity. Aims in your movement direction.",
		"Peas": "A strong 4 in 1 deal. Projectiles have 10x the health and bounce off walls.",
		"Grapes": "A poisonous 4 in 1 deal. Projectiles have 10x the health and bounce off walls and enemies.",
		"Cactus": "Increases the maximum health of the central tank.",
		"Husk": "A husk of what was once a strong insect. Equipping gives you body armor for mob body damage (non-stackable) and max health.",
		"Toxin": "All mobs that touch you will take poison damage.",
		"Dark Spine": "WIth centuries of evolution, this husk of a coral carries a deadly omen. Instantly kills bosses under a certain %.",
		"Cutter": "Quite spiky. Grants you additional body damage. You do not take knockback from mob or projectile body damage while equipped. Does not stack.",
		"Clover": "[PROBABLY BUGGED] Reloads at the start of waves, increasing Lucky Wave chance, which causes double drops. Stacks with other clovers diminishingly. Chance has a minimum of 4 times total squad buff. Lucky & Boss are mutually exclusive.",
		"Horn": "If the current wave has ended, this petal calls for the next wave to start if there are under a certain number of mobs remaining. It also instantly vanquishes all remaining mobs under some rarity without drops.",
		"Dandelion": "Reduces healing effects on its target (reduces heal/s by effect). It's shootable.",
		"Egg": "Chaotically shoots out eggs which spawn a friendly mob that defends you. Careful: if multiple summons touch each other, they die!",
		"Plastic Egg": "Through advanced technology, summons a plastic.",
		"Jellyfish Egg": "It's gonna zap everything to death. Pet Jellyfish deal 12% of their max health as zap damage.",
		"Web": "It shoots out webs which slow down mobs.",
		"Pollen": "Asthmatics beware: this tank leaves pollen scattered everywhere.",
		"Magnet": "Increases drop pickup range. Does not stack. Defends against electrical attacks.",
		"Stick": "A mysterious stick that tries to summon sandstorms but doesn't have enough range to do so.",
		"Salt": "Reflects damage back to the enemy that dealt it.",
		"Soil": "Currently works like a normal soil, but in the future it may increase hp of ALL tanks.",
		"Powder": "Increases movement speed, but decreases health. Does not stack.",
		"Shade": "The remains of a dark soul. Upon being killed, hold on to life for just a bit longer. Damage taken as a shadow is counted as a quarter. Cannot revive other flowers while being a shadow, and cannot be revived shortly after death. Does not stack.",
		"Radiance": "The remains of a bright soul. All damage taken is converted into healing for other flowers in the squad. Does not stack.", 
		"Dust": "Covers yourself in dust, causing all mobs to recalculate which flower they target. During this recalculation, you have 1/4 priority.",
		"Mandible": "[Not sure if this works] Has a 10% chance of doing 20x damage. Critical chance increases to 20% when 3 or more flowers are dead.",
		"Third Eye": "[BUGGED] Increases range of all projectiles. Does not stack.",
		"Bud": "If a flower is dead, the tank breaks and places down a bud! Slowly grows back into a flower, reviving dead teammates.",
		"Bloom": "If a flower is dead, the tank breaks and places down a bloom! Slowly grows back into a bouquet, reviving all dead teammates.",
		"Square": "That's the wrong game!",
		"Pentagon": "That's definitely the wrong game!",
		"Ikea": "Home to the world's greatest Swedish Meatballs!",
		"Rubber": "If a mob hits your flower, it gets bounced away. Does not stack, works while on reload.",
		"Shell": "Grants a shield, giving additional HP. Shield slowly decays while active.",
		"Sponge": "Absorbs 90% of incoming damage and deals it over time. Does not stack. If all sponges equipped die, all absorbed damage is instantly dealt.",
		"Pearl": "A true glass cannon.",
		"Jelly": "Upon contact, repels whatever it touched from the flower.",
		"Fangs": "All damage dealt by this petal heals the flower by the lifesteal %. (It's better than it seems)",
		"Jolt": "Once absorbed, teleports you across the map, then cannot be absorbed again for some time",
		"Lightning": "Activates upon contact with an enemy or projectile. Bounces on enemies and projectiles. Lightning ignores Ant Burrows.",
		"Claw": "Deals a percentage of the mob's remaining health, with a maximum.",
		"Starfish": "Heals the flower but only when it's under 70% health",
		"Air": "It's just air. Inflates you but makes you lose much of your max health, relative to the inflation. Unstackable.",
		"Bubble": "Does absolutely nothing!",
		"Shiny Bubble": "Does nothing, but is sparkly?",
		"Coral": "Converts a percentage of overheal into shield, does not stack. Deals % extra damage based on % health.",
		"Compass": "Glows the color of the highest rarity due to spawn in a wave.",
		"Dark Compass": "Glows the color of the lowest rarity due to spawn in a wave.",
		"Waterlogged Compass": "[VERY BUGGY] Shows you the number of the highest rarity mobs spawning in a wave.",
		"Thomas": "Poor Thomas was going faster than he had ever gone before. He was out of breath and his wheels hurt him, but he had to go on. ‘I shall never be the same again,’ he thought sadly. ‘My wheels will be quite worn out.’ ",
		"Card": "This credit card oozes wealth, attracting the plebeian enemies so much that they spawn faster. Does not stack. Only obtainable through the flowr.fun discord server.",
		"Mini Flower": "uwu so cute <3",
		"Ruby": "A mythical gem infused with the power of friendship.",
		"Sapphire": "A mythical gem infused with the power of transformation.",
		"Emerald": "A mythical gem infused with the power of genesis.",
		"Amulet of Divergence": "An ancient relic believed to have the power of creating a false reality. Limited use per player per game. (Attack or defend to absorb differently; only usable after wave spawning ends; new spawn-waves do not save after use)",
		"Amulet of Grace": "An ancient relic believed to have the power of delaying the inevitable. Limited use per player per game. (Absorbs into the player; only usable after wave spawning ends)",
		"Amulet of Time": "An ancient relic believed to have the power of manipulating time. Slows down every mob by 50% until the next wave.",
		"Blood Stinger": "This stinger demands a sacrifice... Each hit deals damage back to the flower.",
		"Blood Leaf": "This leaf is imbued with the blood of the fallen, growing 1% stronger every life the squad takes. Eventually your shoulders will crumble beneath the weight of your sins. Sins reset if all leaves are unequipped, or upon death.",
		"Blood Corn": "This corn grows darker by the second. For every second this corn lives, it deals 2% more damage but 4% more self-damage. Caps at 1 minute.",
		"Blood Light": "This light demands a sacrifice... Each hit deals damage back to the flower.",
		"Blood Rose": "If enough mobs die before the rose absorbs, you get stacking temporary healing. Failing removes previous stacks & deals self-damage.",
		"Shiny Wing": "The faster it goes, the more damage it does!",
		"Cash": "The sense of cash attracts higher rarity mobs. Their greed forces the room in to higher waves.",
		"Shard of Divergence": "The instability of this shard destroys the fabric of reality, revealing the in-between. The transformation rips the shard to atoms, destroying it permanently.",
		"Shard of Time": "This shard rips open the space-time continuum. The room falls through, re-emerging at an earlier wave. During this process, the shard is lost to the void...",
		"Shard of Grace": "Upon usage, this shard prevents an untimely demise. The next wave is forced back, instilling a sense of hope and relief. This, however, shatters the shard, starting the next wave."
	},
	enemies: {
		"Rock": "It's just a rock.",
		"Soil": "Some soil is on the ground, come pick it up.",
		"Ladybug": "Cute and harmless.",
		"Dark Ladybug": "Not as cute and harmless.",
		"Baby Ant": "Weak and defenseless, but big dreams.",
		"Worker Ant": "Quite tempermental, and chases after you if provoked.",
		"Baby Fire Ant": "Contrary to popular belief, the baby has the freshest & strongest poison. It's still weak and defenseless, but you better not touch it.",
		"Worker Fire Ant": "Quite tempermental, it'll poison you if provoked.",
		"Soldier Ant": "It's got wings and it's ready to use them.", 
		"Soldier Fire Ant": "Run. It has wings and it's poisonous too.",
		"Queen Ant": "You've messed up if she's chasing you",
		"Queen Shiny Ant": "How did you summon this thing and why does it exist",
		"Queen Fire Ant": "You're screwed. Why did you mess with her?",
		"Soldier Shiny Ant": "Why is it shiny???",
		"Desert Centipede": "It's quite fast, but it minds its own business.",
		"Evil Desert Centipede": "It's got a crazy tan.",
		"Shiny Ladybug": "Shiny, cute, and relatively harmless.",
		"Beetle": "It's hungry and flowers are its favorite meal.", 
		"Bee": "Don't touch it. It stings.",
		"Spider": "Spooky.",//"Quick and aggressive, but pretty weak.",
		"Tarantula": "Surprisingly friendly, unless attacked.",
		"Evil Centipede": "This one loves flowers.",
		"Dandelion": "Shoots out its seeds if its in danger.",
		"Fire Ant Burrow": "Careful, get too close and ants will come out.",
		"Locust": "Avenges its friends.",
		"Cactus": "It's spiky, be careful.",
		"Scorpion": "It's got a poisonous stinger, and it's ready to use it.",
		"Sandstorm": "It's quite unpredictable.",
		"Sandstone": "A compressed stone of pure sand. Causes a sandstorm if broken.",
		"Coral": "Once it perceives danger, it will hide and take much less damage.",
		"Hornet": "These aren't quite as nice as the little bees",//"Absolute bully.",
		"Rock Tank": "Get the reference?",
		"Centipede": "It's just there minding its own business.",
		"Desert Moth": "Flies around looking for flowers to land on. It has a hard time flying slowly.",
		"Moonlit Frog": "Comes out every hour on the clock. Trapped within a body shrouded in darkness, this frog carries a quiet spirit, clinging to the faintest whisper of light.",
		"Sunlit Frog": "Goes into hiding every hour on the clock. Beneath its cheerful grin and radiant glow, this frog harbors a soul scorched by regret; a vow to never let their friends down again.",
		"Ruby Frog": "Within this frog lies the spirit of rubyflarm. Very real",
		"Poison Dart Frog": "Careful, it's incredibly toxic!",
		"FireMissile": "Don't let it touch you, it really hurts.",
		"Square": "Wrong game.",
		"Pentagon": "That's definitely the wrong game!",
		"Hexagon": "ƬӇЄ ӇЄҲƛƓƠƝ ӇƛƧ ƁЄЄƝ ƔƠƬЄƊ ƠƲƬ, ƧƬЄƛԼƖƝƓ ӇƛԼƑ ƠƑ ƬӇЄ ƇƦЄƊƖƬƧ. ƬӇЄ ƦЄMƛƖƝƖƝƓ ƇƦЄƊƖƬ ӇƛƧ ƁЄЄƝ MƲԼƬƖƤԼƖЄƊ ƁƳ -6.66Ҳ.",
		"Bubble": "Pop",
		"Sponge": "It's just a sponge. Pretty harmless.",
		"Crab": "It's pretty angry.",
		"Starfish": "Runs away to heal when it's injured",
		"BudLeech": "It targets your buds.",
		"Leech": "Don't let it attach on you: it'll slowly eat away your health. (1 body damage hit every second)",
		"Electric Eel": "Once attached, deals lightning damage across the entire squad. (1 body damage lightning every second)",
		"Jellyfish": "The master of electricity. Zaps you if you get too close. (Zap damage is 1.5x body damage)",
		"Shell": "Just minding its own business, but it'll protect its pearls at all costs",
		"Plastic": "It's polluting the ocean!",
		"Shiny Plastic": "A piece of trash thrown out by a very wealthy individual. Covered with the glint of their guilt.",
		"Sea Urchin": "It's spiky, runs fast, and shoots at you when it's mad.",
		"Missile": "It's fast and it hurts.",
		"FireMissile": "It's really spiky.",
		"ScorpionMissile": "Now with an extra ingredient: Poison!",
		"UrchinMissile": "It's not very strong, but it's slightly poisonous.",
		"DandelionMissile": "Gets released when the Dandelion is in trouble.",
		"RockMissile": "It's slow but it hurts.",
		"BigRockMissile": "This one really hurts",
		"BigDesertMissile": "This one really hurts",
		"BiggestDesertMissile": "This one really hurts",
		"LocustMissile": "It splits",
		"SplitLocustMissile": "It's split",
		"PearlMissile": "It's a pearl, and shootable",
		"Ant Burrow": "Ants come out.",
		"Tree": "Probably hiding some stuff inside",
		"Root": "Decays in 8 seconds, kill it before it's gone for drops!",
		"Shiny Ant Burrow": "An extremely rare hole. Ancient tales say that the finder is granted infinite wisdom.",
		"Sea Floor Burrow": "It hides numerous mobs within. Rumors say that the powerful ones hold much more dangerous creatures.",
		"Ocean Ladybug": "A creature from ancient myths.",
		"Agar.io Cell": "Wrong game. You're so far off that it's impressive",
		"1v1text": "Good luck!",
		"BossRose": "Heals the boss alive!",
		"BossRose2": "Heals the boss alive!",
		"BossBud": "Kill it before it summons dead allies!",
		"BossTrident": "Deals constant damage to all flowers!",
		"Whirlpool": "Don't get caught up in it! Trinket of the Sea is only droppable in Beach.",
		"Lilypad": "A circular plant floating on top of the water, yet to bloom. Comes in large quantities.",
		"Flowering Lilypad": "This Lilypad has bloomed to show its beauty. Harvesting the flower could help mitigate poison if used right.",
		"Shiny Lilypad": "This one has soaked so much sunlight that it begin to change color and become aggressive, wait a minute...",
	}
}

window.officialBiomes = ['garden', 'desert', 'ocean', '1v1'];

canvas.w = window.innerWidth;
canvas.h = window.innerHeight;

// defining stuff
let dt = 0;
const onLoadFunctions = [];

// if(window.msgpackr === undefined){
// 	window.msgpackr = {}//{pack: () => {}, unpack: () => {}};
// }